set encoding=utf-8

set nocompatible

set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smartindent
set smarttab
set ignorecase
set autowrite
set nonumber
set norelativenumber
set ruler
set ruf=%30(%=%#LineNr#%.50F\ [%{strlen(&ft)?&ft:'none'}]\ %l:%c\ %p%%%)
set showmode

set t_vb=

let mapleader=" "

if v:version >= 800
  set nofixendofline
  set listchars=space:.,trail:*,nbsp:*,extends:>,precedes:<,tab:\|>
  set foldmethod=manual
  set nofoldenable
endif

match IncSearch '\s\+$'
set textwidth=72
set spc=

set scrolloff=7

set nobackup
set noswapfile
set nowritebackup

set hlsearch
set incsearch
set linebreak

set hidden

if has("syntax")
  syntax enable
endif

set ttyfast

set clipboard=unnamedplus

nnoremap <Esc> :nohlsearch<CR>

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
