[colors.primary]
background = '#000000'
foreground = '#e6edf3'

[colors.normal]
black   = '#0d1117'
red     = '#ff7b72'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#76e3ea'
white   = '#b1bac4'

[colors.bright]
black   = '#7d8590'
red     = '#ffa198'
green   = '#6bdb7f'
yellow  = '#f2cc60'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#b3f0ff'
white   = '#f0f6fc'
