[colors.primary]
background = '#ffffff'
foreground = '#000000'

[colors.normal]
black   = '#e5e5e5'
red     = '#ff4444'
green   = '#44ff44'
yellow  = '#ffff55'
blue    = '#4444ff'
magenta = '#ff44ff'
cyan    = '#44ffff'
white   = '#000000'

[colors.bright]
black   = '#bfbfbf'
red     = '#ff8888'
green   = '#88ff88'
yellow  = '#ffff88'
blue    = '#8888ff'
magenta = '#ff88ff'
cyan    = '#88ffff'
white   = '#000000'

