[colors.primary]
background = '#ffffff'
foreground = '#24292e'

[colors.normal]
black   = '#24292e'
red     = '#d1242f'
green   = '#1f883d'
yellow  = '#e3b341'
blue    = '#0969da'
magenta = '#6f42c1'
cyan    = '#1b7c83'
white   = '#f6f8fa'

[colors.bright]
black   = '#57606a'
red     = '#d73a49'
green   = '#28a745'
yellow  = '#dbab09'
blue    = '#2188ff'
magenta = '#8a63d2'
cyan    = '#3192aa'
white   = '#ffffff'
